name: EUvsVirus_ProjectClusters
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - beautifulsoup4=4.9.0
  - blas=1.0
  - bleach=3.1.4
  - ca-certificates=2020.4.5.1
  - catalogue=1.0.0
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - intel-openmp=2020.0
  - ipykernel=5.2.1
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.2
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.10
  - mkl_random=1.1.1
  - murmurhash=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - notebook=5.2.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1
  - plac=0.9.6
  - preshed=3.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pyzmq=18.0.2
  - qt=5.9.7
  - qtconsole=4.7.3
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.13.0
  - setuptools=46.2.0
  - sip=4.19.8
  - six=1.14.0
  - soupsieve=2.0
  - spacy=2.2.4
  - sqlite=3.31.1
  - srsly=1.0.2
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.4.0
  - tk=8.6.8
  - tornado=6.0.4
  - tqdm=4.46.0
  - traitlets=4.3.3
  - wasabi=0.6.0
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - emoji==0.5.4
    - en-core-web-md==2.2.5
    - spacymoji==2.0.0

